# Generated by Django 2.2 on 2020-01-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('duration', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.BigIntegerField()),
                ('domain', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('duration', models.BigIntegerField()),
                ('marketing_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('tel', models.FloatField()),
                ('level', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivage.Development')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivage.Formation')),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivage.Marketing')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('tel1', models.BigIntegerField(default='')),
                ('address', models.TextField()),
                ('cadre', models.CharField(max_length=200)),
                ('rib', models.TextField()),
                ('description', models.TextField()),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivage.Development')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivage.Formation')),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivage.Marketing')),
            ],
        ),
    ]
