# Generated by Django 2.2.9 on 2020-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivage', '0007_auto_20200124_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='product',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
